### ISSUE TITLE
Adding go-redis Support

### ISSUE THREAD

**Issue by rawberg** [marselester/gopher-celery#1]
Thanks for taking the time to fork gocelery and support V2 protocol! Exactly what I was looking for. I'd like to take a pass at adding support for go-redis in addition to redigo. Any guidance on how you'd like to see that implemented? One option would be to have two Redis brokers `redis/RedigoBroker` and `redis/GoRedisBroker`. Another approach would be to try to support both in the existing broker. Maybe adding to the existing `Broker` struct so it can hold a go-redis instance?

**Comment by marselester** [comment]
Hi! That sounds good. Let's isolate the implementation in `goredis` package so we would have a similar API.

```go
goredis.NewBroker(goredis.WithSomething(...))
```

Note, the `redis.Option` and `goredis.Option` types should be renamed to `BrokerOption` because there might be a `BackendOption` in the future.

`move2back` can be copy-pasted or moved into `internal/broker/move2back.go`.
