### ISSUE TITLE
Dynamic registration

### ISSUE THREAD

**Issue by dcrystalj** [marselester/gopher-celery#6]
Is there any particular reason why you limited tasks registration ?
```
// Note, the method is not concurrency safe.
// The tasks mustn't be registered after the app starts processing tasks.
func (a *App) Register(path, queue string, task TaskF) {
...
```

I would need to Register/Unregister tasks on the fly.

**Comment by marselester** [comment]
Sorry that it doesn't cover your use case. I've made this library to solve a particular problem, i.e., to efficiently produce and consume Celery tasks on Go side. I deliberately kept things simple and didn't consider adding other Celery features when designing the library because they come at a cost of extra complexity, maintenance burden, and performance penalty. So registering all the tasks before Gopher Celery starts processing the queues is a straightforward approach that doesn't require any synchronization in the app and on the broker side. If I added that feature, the synchronization would affect performance of the library.

In my ~10 years of anecdotal experience working with Celery on Python side (mostly Django) I've never needed to dynamically register or unregister tasks in runtime, so most likely it is not a common use case. Therefore I don't think it's viable to implement it in this project. Thank you for understanding.

**Comment by dcrystalj** [comment]
Didn't do much deep dive but do you think making task and taskQueue map safe for concurrent access will do the trick?
I am willing to sacrifice a little speed for this option.

**Comment by marselester** [comment]
Yeah, I would go with a `sync.Map` for `task` and `taskQueue` in `celery.go`. Access to `br.queues` should be synchronized on a broker side as well https://github.com/marselester/gopher-celery/blob/main/redis/broker.go. Also, `a.conf.broker.Observe(qq)` should be called when a task is registered/unregistered.

**Comment by dcrystalj** [comment]
Thank you sir. Really appreciate your work here.
Will fork it out and link it here later.

**Comment by marselester** [comment]
You're welcome 👍

**Comment by dcrystalj** [comment]
here is the fork if anyone else is interesed https://github.com/marselester/gopher-celery
